function up = load_user_paths()
%LOAD_USER_PATHS Load gitignored user_paths.m or fall back to example defaults.
    projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    userFile = fullfile(projectRoot, 'user_paths.m');

    if isfile(userFile)
        up = user_paths();
        return;
    end

    warning('load_user_paths:UsingExample', ...
        'user_paths.m not found — using defaults from user_paths.example.m');
    up = struct( ...
        'outputRoot', 'C:\ResearchData\Results\Core', ...
        'lastCohort', '', ...
        'lastHSubInput', '', ...
        'lastWaveInput', '', ...
        'lastAcrossInput', '', ...
        'lastPlotMode', 'development');
end
