function FB = wavelet_make_filterbank(nSamples, TsMinutes, cfg)
%WAVELET_MAKE_FILTERBANK Morlet CWT filter bank (amor, 60–1590 min).
    if nargin < 3, cfg = core_defaults(); end
    FB = cwtfilterbank('SignalLength', nSamples, ...
        'SamplingPeriod', minutes(TsMinutes), ...
        'PeriodLimits', minutes(cfg.wavelet.periodLimitsMinutes), ...
        'Wavelet', cfg.wavelet.waveletName);
end
