%% ========================================================================
% Script 3 (v1 - Raw vs Selective-HSub ultradian period validation)
% File: Validate_RawVsSelectiveHSub_Periods_v1.m
% ========================================================================
% Purpose
%   This script is the gatekeeper for the validated-Raw ultradian pipeline.
%
%   It loads PeriodCandidates_Long tables generated by Behav_wavelet_v12.m,
%   compares Raw ultradian ridge candidates against Selective-HSub candidates,
%   and creates a validated carry-forward map for downstream analyses.
%
% Conceptual rule
%   - Raw data remain the biological signal for all final rhythm characterisation.
%   - Selective-HSub is used only as a validation layer.
%   - Full Ladder outputs are retained as aggressive-subtraction sensitivity flags.
%
% Primary validation mode
%   Raw UR candidate is carried forward only if a corresponding Selective-HSub
%   candidate in SEL_P360 is detected within a pre-specified period tolerance.
%
% Main outputs
%   HSubSupported_PeriodMap.xlsx
%   HSubSupported_PeriodMap.mat
%   Figures/ validation figures as JPEG at 600 DPI
%
% Expected input
%   AcrossPhotoperiod_Input/WP_Summary__*.mat files from Behav_wavelet_v12.m
%   Each .mat should contain:
%       pkgS.tables.PeriodCandidates_Long
%
% MATLAB: R2025a/R2025b
% ========================================================================

clearvars; close all; clc;

%% ----------------------------- SETTINGS ---------------------------------
SCRIPT_NAME    = 'Validate_RawVsSelectiveHSub_Periods_v1';
SCRIPT_VERSION = '1.0';
RUN_TIMESTAMP  = string(datetime('now','Format','yyyy-MM-dd HH:mm:ss'));

% Primary validation settings
PRIMARY_HSUB_MODE       = "SEL_P360";
SECONDARY_HSUB_MODES    = ["SEL_P60"];
SENSITIVITY_HSUB_MODES  = ["FL_P360", "FL_P60"];
PRIMARY_PHASE           = "All";

% Bands
UR_BANDS = ["UR_1_3", "UR_3_6", "UR_6_9", "UR_9_12", "UR_12_18"];
HARMONIC_SENSITIVE_BANDS = ["UR_12_18"];

% Matching and QC thresholds
PERIOD_TOLERANCE_FRAC = 0.15;              % approximately +/-15% period agreement
PERIOD_TOLERANCE_LOG2 = log2(1 + PERIOD_TOLERANCE_FRAC);
MIN_RAW_RIDGE_COVERAGE  = 0.50;
MIN_RAW_COI_VALID_FRAC  = 0.50;
MIN_HSUB_RIDGE_COVERAGE = 0.50;
MIN_HSUB_COI_VALID_FRAC = 0.50;
REQUIRE_RAW_PASSQC  = true;
REQUIRE_HSUB_PASSQC = true;

% Output
SAVE_DPI = 600;
FIG_EXT  = '.jpg';

%% ----------------------------- SELECT INPUT -----------------------------
fprintf('\n%s\n', SCRIPT_NAME);
fprintf('Select the AcrossPhotoperiod_Input folder containing WP_Summary__*.mat files.\n');

handoffDir = uigetdir(pwd, 'Select AcrossPhotoperiod_Input folder containing WP_Summary__*.mat');
if isequal(handoffDir,0)
    fprintf('No folder selected. Exiting.\n');
    return;
end
handoffDir = char(handoffDir);

sumFiles = dir(fullfile(handoffDir, 'WP_Summary__*.mat'));
if isempty(sumFiles)
    error('No WP_Summary__*.mat files found in: %s', handoffDir);
end

outRoot = fullfile(handoffDir, 'RawVsSelectiveHSub_PeriodValidation');
figDir  = fullfile(outRoot, 'Figures');
logDir  = fullfile(outRoot, 'Logs');
ensure_dir(outRoot); ensure_dir(figDir); ensure_dir(logDir);

logPath = fullfile(logDir, sprintf('%s_Log_%s.txt', SCRIPT_NAME, datestr(now,'yyyymmdd_HHMMSS')));
LOG = fopen(logPath,'w');
cleanupObj = onCleanup(@() fclose_if_open(LOG)); %#ok<NASGU>
log_line(LOG, '%s started at %s', SCRIPT_NAME, RUN_TIMESTAMP);
log_line(LOG, 'Input folder: %s', handoffDir);
log_line(LOG, 'Found %d WP_Summary files.', numel(sumFiles));

%% ----------------------------- LOAD TABLES ------------------------------
allCandidates = table();
loadRows = {};
loadHdr = {'SummaryMat','Loaded','NRows','Message'};

for i = 1:numel(sumFiles)
    matPath = fullfile(sumFiles(i).folder, sumFiles(i).name);
    try
        S = load(matPath);
        if isfield(S, 'pkgS') && isfield(S.pkgS, 'tables') && isfield(S.pkgS.tables, 'PeriodCandidates_Long')
            T = S.pkgS.tables.PeriodCandidates_Long;
        elseif isfield(S, 'PeriodCandidates_Long')
            T = S.PeriodCandidates_Long;
        else
            error('No pkgS.tables.PeriodCandidates_Long table found.');
        end

        T = standardise_candidate_table(T, matPath);
        allCandidates = vertcat_compatible(allCandidates, T); %#ok<AGROW>
        loadRows(end+1,:) = {matPath, true, height(T), 'OK'}; %#ok<SAGROW>
        log_line(LOG, 'Loaded %s (%d rows).', matPath, height(T));
    catch ME
        loadRows(end+1,:) = {matPath, false, 0, ME.message}; %#ok<SAGROW>
        log_line(LOG, 'FAILED loading %s: %s', matPath, ME.message);
    end
end

LoadSummary = cell2table(loadRows, 'VariableNames', loadHdr);

if isempty(allCandidates) || height(allCandidates) == 0
    error('No PeriodCandidates_Long rows were loaded. See log: %s', logPath);
end

allCandidates.GlobalCandidateRow = (1:height(allCandidates))';
allCandidates = movevars(allCandidates, 'GlobalCandidateRow', 'Before', 1);

%% ----------------------------- PREPARE DATA -----------------------------
% Keep primary phase and UR bands only for validation.
T = allCandidates;
T.SourceNorm = upper(string(T.Source));
T.ModeNorm   = upper(string(T.HSubResidualMode));
T.PhaseNorm  = string(T.Phase);
T.BandNorm   = string(T.BandName);

isUR = ismember(T.BandNorm, UR_BANDS);
isPhase = strcmpi(T.PhaseNorm, PRIMARY_PHASE);
Tval = T(isUR & isPhase, :);

if isempty(Tval) || height(Tval) == 0
    error('No ultradian candidate rows found for Phase=%s.', PRIMARY_PHASE);
end

rawMask = strcmpi(Tval.SourceNorm, 'RAW');
hsubMask = strcmpi(Tval.SourceNorm, 'HSUB');
primaryMask = hsubMask & strcmpi(Tval.ModeNorm, upper(PRIMARY_HSUB_MODE));

RawCandidates = Tval(rawMask, :);
PrimaryHSubCandidates = Tval(primaryMask, :);

if isempty(RawCandidates) || height(RawCandidates) == 0
    error('No Raw ultradian candidates found in PeriodCandidates_Long.');
end
if isempty(PrimaryHSubCandidates) || height(PrimaryHSubCandidates) == 0
    warning('No primary HSub candidates found for mode %s. No candidates will be carried forward.', PRIMARY_HSUB_MODE);
end

RawCandidates.EligibleRaw = candidate_passes_qc(RawCandidates, MIN_RAW_RIDGE_COVERAGE, MIN_RAW_COI_VALID_FRAC, REQUIRE_RAW_PASSQC);
PrimaryHSubCandidates.EligibleHSub = candidate_passes_qc(PrimaryHSubCandidates, MIN_HSUB_RIDGE_COVERAGE, MIN_HSUB_COI_VALID_FRAC, REQUIRE_HSUB_PASSQC);

log_line(LOG, 'Raw UR candidate rows: %d', height(RawCandidates));
log_line(LOG, 'Primary HSub UR candidate rows (%s): %d', PRIMARY_HSUB_MODE, height(PrimaryHSubCandidates));
log_line(LOG, 'Eligible Raw candidates: %d', sum(RawCandidates.EligibleRaw));
log_line(LOG, 'Eligible primary HSub candidates: %d', sum(PrimaryHSubCandidates.EligibleHSub));

%% ----------------------------- PRIMARY MATCHING -------------------------
Matched = build_primary_matches(RawCandidates, PrimaryHSubCandidates, PRIMARY_HSUB_MODE, ...
    PERIOD_TOLERANCE_LOG2, PERIOD_TOLERANCE_FRAC, HARMONIC_SENSITIVE_BANDS);

% Add secondary Selective and Full Ladder sensitivity fields.
modeList = unique([SECONDARY_HSUB_MODES(:); SENSITIVITY_HSUB_MODES(:)], 'stable');
for m = 1:numel(modeList)
    mode = modeList(m);
    Hm = Tval(hsubMask & strcmpi(Tval.ModeNorm, upper(mode)), :);
    if ~isempty(Hm)
        Hm.EligibleHSub = candidate_passes_qc(Hm, MIN_HSUB_RIDGE_COVERAGE, MIN_HSUB_COI_VALID_FRAC, REQUIRE_HSUB_PASSQC);
    end
    Matched = add_mode_match_columns(Matched, Hm, mode, PERIOD_TOLERANCE_LOG2);
end

Matched = add_full_ladder_sensitivity_status(Matched, SENSITIVITY_HSUB_MODES);
Matched = add_final_validation_class(Matched);

CarryForward = Matched(Matched.CarryForward, :);
RawOnly_NotCarriedForward = Matched(~Matched.CarryForward, :);

HSubOnly_ResidualFeatures = build_hsub_only_table(RawCandidates, PrimaryHSubCandidates, ...
    PERIOD_TOLERANCE_LOG2, PRIMARY_HSUB_MODE);

FullLadder_Sensitivity = build_full_ladder_sensitivity_table(Matched, SENSITIVITY_HSUB_MODES);
Retention_ByBand = make_retention_summary(Matched, "BandName");
Retention_ByPhotoperiod = make_retention_summary(Matched, "Photoperiod_h");
Retention_ByPhotoperiodBand = make_retention_summary(Matched, ["Photoperiod_h", "BandName"]);
QC_Flags = build_qc_flags(Matched);

log_line(LOG, 'Carry-forward candidates: %d', height(CarryForward));
log_line(LOG, 'Raw-only/not-carried-forward candidates: %d', height(RawOnly_NotCarriedForward));
log_line(LOG, 'HSub-only residual features: %d', height(HSubOnly_ResidualFeatures));

%% ----------------------------- SETTINGS TABLE ---------------------------
Settings = table();
Settings.ScriptName = string(SCRIPT_NAME);
Settings.ScriptVersion = string(SCRIPT_VERSION);
Settings.Timestamp = RUN_TIMESTAMP;
Settings.InputFolder = string(handoffDir);
Settings.PrimaryHSubMode = PRIMARY_HSUB_MODE;
Settings.SecondaryHSubModes = join(SECONDARY_HSUB_MODES, '; ');
Settings.SensitivityHSubModes = join(SENSITIVITY_HSUB_MODES, '; ');
Settings.PrimaryPhase = PRIMARY_PHASE;
Settings.PeriodToleranceFrac = PERIOD_TOLERANCE_FRAC;
Settings.PeriodToleranceLog2 = PERIOD_TOLERANCE_LOG2;
Settings.MinRawRidgeCoverage = MIN_RAW_RIDGE_COVERAGE;
Settings.MinRawCOIValidFrac = MIN_RAW_COI_VALID_FRAC;
Settings.MinHSubRidgeCoverage = MIN_HSUB_RIDGE_COVERAGE;
Settings.MinHSubCOIValidFrac = MIN_HSUB_COI_VALID_FRAC;
Settings.RequireRawPassQC = REQUIRE_RAW_PASSQC;
Settings.RequireHSubPassQC = REQUIRE_HSUB_PASSQC;
Settings.URBands = join(UR_BANDS, '; ');
Settings.HarmonicSensitiveBands = join(HARMONIC_SENSITIVE_BANDS, '; ');

%% ----------------------------- WRITE OUTPUTS ----------------------------
outXLSX = fullfile(outRoot, 'HSubSupported_PeriodMap.xlsx');
outMAT  = fullfile(outRoot, 'HSubSupported_PeriodMap.mat');
delete_if_exists(outXLSX);

write_output_workbook(outXLSX, Settings, LoadSummary, allCandidates, Matched, CarryForward, ...
    RawOnly_NotCarriedForward, HSubOnly_ResidualFeatures, FullLadder_Sensitivity, ...
    Retention_ByBand, Retention_ByPhotoperiod, Retention_ByPhotoperiodBand, QC_Flags);

validationMap = struct();
validationMap.Settings = Settings;
validationMap.LoadSummary = LoadSummary;
validationMap.AllPeriodCandidates = allCandidates;
validationMap.Matched_Periods_All = Matched;
validationMap.CarryForward_Periods = CarryForward;
validationMap.RawOnly_NotCarriedForward = RawOnly_NotCarriedForward;
validationMap.HSubOnly_ResidualFeatures = HSubOnly_ResidualFeatures;
validationMap.FullLadder_Sensitivity = FullLadder_Sensitivity;
validationMap.Retention_ByBand = Retention_ByBand;
validationMap.Retention_ByPhotoperiod = Retention_ByPhotoperiod;
validationMap.Retention_ByPhotoperiodBand = Retention_ByPhotoperiodBand;
validationMap.QC_Flags = QC_Flags;

save(outMAT, 'validationMap', '-v7.3');

%% ----------------------------- FIGURES ----------------------------------
try
    make_validation_figures(Matched, PrimaryHSubCandidates, figDir, SAVE_DPI, FIG_EXT, PRIMARY_HSUB_MODE);
catch ME
    warning('Figure generation failed: %s', ME.message);
    log_line(LOG, 'Figure generation failed: %s', ME.message);
end

log_line(LOG, 'Output workbook: %s', outXLSX);
log_line(LOG, 'Output MAT: %s', outMAT);
log_line(LOG, '%s finished at %s', SCRIPT_NAME, string(datetime('now','Format','yyyy-MM-dd HH:mm:ss')));

fprintf('\nDone.\n');
fprintf('Output folder:\n  %s\n', outRoot);
fprintf('Workbook:\n  %s\n', outXLSX);
fprintf('MAT file:\n  %s\n', outMAT);

%% ========================================================================
% LOCAL FUNCTIONS
% ========================================================================

function T = standardise_candidate_table(T, sourcePackage)
    if ~istable(T)
        error('PeriodCandidates_Long object is not a table.');
    end

    strVars = {'File','SignalID','ConditionParsed','Source','HSubResidualMode','Phase','BandName','CandidateID','QCReason'};
    numVars = {'Photoperiod_h','CandidateRank','MedianRidgePeriod_h','IQR_RidgePeriod_h', ...
        'MeanBandPower_log10','SDBandPower_log10','MeanRidgePower_log10','SDRidgePower_log10', ...
        'RidgeCoverageFrac','COIValidFrac','ValidPointCount','TotalPointCount'};
    logVars = {'PassQC'};

    for i = 1:numel(strVars)
        v = strVars{i};
        if ~ismember(v, T.Properties.VariableNames)
            T.(v) = strings(height(T),1);
        else
            T.(v) = string(T.(v));
        end
    end

    for i = 1:numel(numVars)
        v = numVars{i};
        if ~ismember(v, T.Properties.VariableNames)
            T.(v) = nan(height(T),1);
        else
            T.(v) = to_double_col(T.(v));
        end
    end

    for i = 1:numel(logVars)
        v = logVars{i};
        if ~ismember(v, T.Properties.VariableNames)
            T.(v) = false(height(T),1);
        else
            T.(v) = to_logical_col(T.(v));
        end
    end

    % Fill missing candidate IDs if needed.
    missingCID = ismissing(T.CandidateID) | strlength(T.CandidateID) == 0;
    if any(missingCID)
        for r = find(missingCID(:))'
            T.CandidateID(r) = sprintf('%s|%s|%s|%s|%s|%s|%03d', ...
                char(T.File(r)), char(T.SignalID(r)), char(T.Source(r)), char(T.HSubResidualMode(r)), ...
                char(T.Phase(r)), char(T.BandName(r)), r);
        end
    end

    if ~ismember('SourcePackage', T.Properties.VariableNames)
        T.SourcePackage = repmat(string(sourcePackage), height(T), 1);
    else
        T.SourcePackage = string(T.SourcePackage);
    end

    keepVars = [{'SourcePackage'}, strVars, numVars, logVars];
    T = T(:, keepVars);
end

function out = vertcat_compatible(A, B)
    if isempty(A)
        out = B;
        return;
    end
    allNames = unique([A.Properties.VariableNames, B.Properties.VariableNames], 'stable');
    A = add_missing_vars(A, allNames);
    B = add_missing_vars(B, allNames);
    out = [A(:,allNames); B(:,allNames)];
end

function T = add_missing_vars(T, names)
    for i = 1:numel(names)
        n = names{i};
        if ~ismember(n, T.Properties.VariableNames)
            T.(n) = strings(height(T),1);
        end
    end
end

function x = to_double_col(x)
    if isnumeric(x)
        x = double(x(:));
    elseif islogical(x)
        x = double(x(:));
    else
        x = str2double(string(x(:)));
    end
end

function x = to_logical_col(x)
    if islogical(x)
        x = x(:);
    elseif isnumeric(x)
        x = x(:) ~= 0;
    else
        s = lower(strtrim(string(x(:))));
        x = ismember(s, ["true","1","yes","y","pass","passed"]);
    end
end

function tf = candidate_passes_qc(T, minCoverage, minCOI, requirePassQC)
    tf = true(height(T),1);
    if requirePassQC && ismember('PassQC', T.Properties.VariableNames)
        tf = tf & logical(T.PassQC);
    end
    if ismember('RidgeCoverageFrac', T.Properties.VariableNames)
        tf = tf & T.RidgeCoverageFrac >= minCoverage;
    end
    if ismember('COIValidFrac', T.Properties.VariableNames)
        tf = tf & T.COIValidFrac >= minCOI;
    end
    if ismember('MedianRidgePeriod_h', T.Properties.VariableNames)
        tf = tf & isfinite(T.MedianRidgePeriod_h) & T.MedianRidgePeriod_h > 0;
    end
end

function M = build_primary_matches(Raw, HSub, primaryMode, tolLog2, tolFrac, harmonicBands)
    varNames = {'File','SignalID','ConditionParsed','Photoperiod_h','Phase','BandName', ...
        'RawGlobalCandidateRow','RawCandidateID','RawCandidateRank','RawPeriod_h','RawIQR_h', ...
        'RawMeanBandPower_log10','RawMeanRidgePower_log10','RawRidgeCoverageFrac','RawCOIValidFrac','RawPassQC', ...
        'PrimaryHSubMode','PrimaryHSubGlobalCandidateRow','PrimaryHSubCandidateID','PrimaryHSubPeriod_h','PrimaryHSubIQR_h', ...
        'PrimaryHSubMeanRidgePower_log10','PrimaryHSubRidgeCoverageFrac','PrimaryHSubCOIValidFrac','PrimaryHSubPassQC', ...
        'AbsLog2PeriodDiff','PeriodDiffPercent','WithinTolerance','MatchStatus','CarryForward','HarmonicSensitive12hFlag','QCFlag','SourcePackage'};

    rows = cell(height(Raw), numel(varNames));

    for i = 1:height(Raw)
        r = Raw(i,:);
        rawOK = logical(r.EligibleRaw);
        rawP = r.MedianRidgePeriod_h;
        harmonicFlag = ismember(string(r.BandName), harmonicBands);

        hsubAny = table();
        hsubElig = table();
        if ~isempty(HSub)
            keyMask = same_key_mask(HSub, r);
            hsubAny = HSub(keyMask, :);
            hsubElig = HSub(keyMask & HSub.EligibleHSub, :);
        end

        best = table();
        absLog2Diff = NaN;
        pctDiff = NaN;
        withinTol = false;

        if rawOK && ~isempty(hsubElig)
            d = abs(log2(rawP ./ hsubElig.MedianRidgePeriod_h));
            [absLog2Diff, idx] = min(d);
            best = hsubElig(idx,:);
            pctDiff = 100 * abs(rawP - best.MedianRidgePeriod_h) / rawP;
            withinTol = absLog2Diff <= tolLog2;
        elseif ~rawOK && ~isempty(hsubAny)
            d = abs(log2(rawP ./ hsubAny.MedianRidgePeriod_h));
            [absLog2Diff, idx] = min(d);
            best = hsubAny(idx,:);
            pctDiff = 100 * abs(rawP - best.MedianRidgePeriod_h) / rawP;
            withinTol = false;
        elseif rawOK && isempty(hsubElig) && ~isempty(hsubAny)
            d = abs(log2(rawP ./ hsubAny.MedianRidgePeriod_h));
            [absLog2Diff, idx] = min(d);
            best = hsubAny(idx,:);
            pctDiff = 100 * abs(rawP - best.MedianRidgePeriod_h) / rawP;
            withinTol = false;
        end

        if ~rawOK
            status = "Fail_raw_QC";
            carry = false;
            qc = "Raw_QC_fail";
        elseif isempty(hsubAny)
            status = "Raw_only_not_carried_forward";
            carry = false;
            qc = "No_primary_HSub_candidate";
        elseif isempty(hsubElig)
            status = "Raw_present_primary_HSub_QC_fail";
            carry = false;
            qc = "Primary_HSub_QC_fail";
        elseif withinTol
            status = "HSub_supported_primary";
            carry = true;
            qc = "Pass";
        else
            status = "Raw_present_HSub_period_mismatch";
            carry = false;
            qc = "Period_mismatch";
        end

        if harmonicFlag
            qc = qc + ";Harmonic_sensitive_12h_region";
        end

        [hID,hRow,hP,hIQR,hPow,hCov,hCOI,hPass] = empty_hsub_vals();
        if ~isempty(best)
            hID   = string(best.CandidateID);
            hRow  = best.GlobalCandidateRow;
            hP    = best.MedianRidgePeriod_h;
            hIQR  = best.IQR_RidgePeriod_h;
            hPow  = best.MeanRidgePower_log10;
            hCov  = best.RidgeCoverageFrac;
            hCOI  = best.COIValidFrac;
            hPass = logical(best.PassQC);
        end

        rows(i,:) = {string(r.File), string(r.SignalID), string(r.ConditionParsed), r.Photoperiod_h, string(r.Phase), string(r.BandName), ...
            r.GlobalCandidateRow, string(r.CandidateID), r.CandidateRank, r.MedianRidgePeriod_h, r.IQR_RidgePeriod_h, ...
            r.MeanBandPower_log10, r.MeanRidgePower_log10, r.RidgeCoverageFrac, r.COIValidFrac, rawOK, ...
            string(primaryMode), hRow, hID, hP, hIQR, hPow, hCov, hCOI, hPass, ...
            absLog2Diff, pctDiff, withinTol, status, carry, harmonicFlag, qc, string(r.SourcePackage)};
    end

    M = cell2table(rows, 'VariableNames', varNames);
end

function [hID,hRow,hP,hIQR,hPow,hCov,hCOI,hPass] = empty_hsub_vals()
    hID = string(missing); hRow = NaN; hP = NaN; hIQR = NaN; hPow = NaN; hCov = NaN; hCOI = NaN; hPass = false;
end

function tf = same_key_mask(T, r)
    tf = true(height(T),1);
    tf = tf & strcmpi(string(T.File), string(r.File));
    tf = tf & strcmpi(string(T.SignalID), string(r.SignalID));
    tf = tf & strcmpi(string(T.ConditionParsed), string(r.ConditionParsed));
    tf = tf & abs(T.Photoperiod_h - r.Photoperiod_h) < 1e-9;
    tf = tf & strcmpi(string(T.Phase), string(r.Phase));
    tf = tf & strcmpi(string(T.BandName), string(r.BandName));
end

function M = add_mode_match_columns(M, Hm, mode, tolLog2)
    prefix = matlab.lang.makeValidName(char(mode));
    existsCol = [prefix '_Exists'];
    matchedCol = [prefix '_Matched'];
    periodCol = [prefix '_Period_h'];
    diffCol = [prefix '_DiffPercent'];
    idCol = [prefix '_CandidateID'];
    eligibleCol = [prefix '_EligibleHSub'];

    M.(existsCol) = false(height(M),1);
    M.(matchedCol) = false(height(M),1);
    M.(periodCol) = nan(height(M),1);
    M.(diffCol) = nan(height(M),1);
    M.(idCol) = strings(height(M),1);
    M.(eligibleCol) = false(height(M),1);

    if isempty(Hm) || height(Hm) == 0
        return;
    end

    for i = 1:height(M)
        rawProxy = table();
        rawProxy.File = M.File(i);
        rawProxy.SignalID = M.SignalID(i);
        rawProxy.ConditionParsed = M.ConditionParsed(i);
        rawProxy.Photoperiod_h = M.Photoperiod_h(i);
        rawProxy.Phase = M.Phase(i);
        rawProxy.BandName = M.BandName(i);

        keyMask = same_key_mask(Hm, rawProxy);
        hAny = Hm(keyMask, :);
        if ~isempty(hAny)
            M.(existsCol)(i) = true;
        else
            continue;
        end

        hElig = hAny;
        if ismember('EligibleHSub', hElig.Properties.VariableNames)
            hElig = hElig(hElig.EligibleHSub, :);
        end
        if isempty(hElig)
            continue;
        end

        M.(eligibleCol)(i) = true;
        rawP = M.RawPeriod_h(i);
        d = abs(log2(rawP ./ hElig.MedianRidgePeriod_h));
        [bestD, idx] = min(d);
        best = hElig(idx,:);
        M.(periodCol)(i) = best.MedianRidgePeriod_h;
        M.(diffCol)(i) = 100 * abs(rawP - best.MedianRidgePeriod_h) / rawP;
        M.(idCol)(i) = string(best.CandidateID);
        M.(matchedCol)(i) = bestD <= tolLog2;
    end
end

function M = add_full_ladder_sensitivity_status(M, flModes)
    status = strings(height(M),1);
    for i = 1:height(M)
        if ~M.CarryForward(i)
            status(i) = "Not_applicable_not_carried_forward";
            continue;
        end
        anyExists = false;
        anyMatched = false;
        for j = 1:numel(flModes)
            prefix = matlab.lang.makeValidName(char(flModes(j)));
            existsCol = [prefix '_Exists'];
            matchedCol = [prefix '_Matched'];
            if ismember(existsCol, M.Properties.VariableNames)
                anyExists = anyExists || M.(existsCol)(i);
            end
            if ismember(matchedCol, M.Properties.VariableNames)
                anyMatched = anyMatched || M.(matchedCol)(i);
            end
        end
        if anyMatched
            status(i) = "Selective_supported_and_FullLadder_supported";
        elseif anyExists
            status(i) = "Selective_supported_FullLadder_sensitive";
        else
            status(i) = "Selective_supported_NoFullLadderCandidate";
        end
    end
    M.FullLadderSensitivityStatus = status;
end

function M = add_final_validation_class(M)
    cls = string(M.MatchStatus);
    for i = 1:height(M)
        if M.CarryForward(i)
            cls(i) = "HSub_supported_primary";
            if strcmpi(M.FullLadderSensitivityStatus(i), "Selective_supported_FullLadder_sensitive")
                cls(i) = cls(i) + ";FullLadder_sensitive";
            end
            if M.HarmonicSensitive12hFlag(i)
                cls(i) = cls(i) + ";Harmonic_sensitive_12h_region";
            end
        else
            cls(i) = string(M.MatchStatus(i));
            if M.HarmonicSensitive12hFlag(i)
                cls(i) = cls(i) + ";Harmonic_sensitive_12h_region";
            end
        end
    end
    M.FinalValidationClass = cls;
end

function Honly = build_hsub_only_table(Raw, HSub, tolLog2, primaryMode)
    rows = {};
    hdr = {'File','SignalID','ConditionParsed','Photoperiod_h','Phase','BandName','PrimaryHSubMode', ...
           'HSubGlobalCandidateRow','HSubCandidateID','HSubPeriod_h','HSubRidgeCoverageFrac','HSubCOIValidFrac','HSubPassQC','Reason'};

    if isempty(HSub) || height(HSub) == 0
        Honly = cell2table(cell(0,numel(hdr)), 'VariableNames', hdr);
        return;
    end

    for i = 1:height(HSub)
        h = HSub(i,:);
        if ~logical(h.EligibleHSub), continue; end

        rAny = Raw(same_key_mask(Raw, h), :);
        if isempty(rAny)
            reason = "No_raw_candidate";
            isHOnly = true;
        else
            if ismember('EligibleRaw', rAny.Properties.VariableNames)
                rAny = rAny(rAny.EligibleRaw, :);
            end
            if isempty(rAny)
                reason = "Raw_candidate_QC_fail";
                isHOnly = true;
            else
                d = abs(log2(rAny.MedianRidgePeriod_h ./ h.MedianRidgePeriod_h));
                isHOnly = all(d > tolLog2);
                reason = "No_raw_period_match_within_tolerance";
            end
        end

        if isHOnly
            rows(end+1,:) = {string(h.File), string(h.SignalID), string(h.ConditionParsed), h.Photoperiod_h, string(h.Phase), string(h.BandName), string(primaryMode), ...
                h.GlobalCandidateRow, string(h.CandidateID), h.MedianRidgePeriod_h, h.RidgeCoverageFrac, h.COIValidFrac, logical(h.PassQC), reason}; %#ok<AGROW>
        end
    end

    if isempty(rows)
        Honly = cell2table(cell(0,numel(hdr)), 'VariableNames', hdr);
    else
        Honly = cell2table(rows, 'VariableNames', hdr);
    end
end

function T = build_full_ladder_sensitivity_table(M, flModes)
    baseVars = {'File','SignalID','ConditionParsed','Photoperiod_h','Phase','BandName','RawCandidateID','RawPeriod_h','CarryForward','FullLadderSensitivityStatus','FinalValidationClass'};
    extraVars = {};
    for j = 1:numel(flModes)
        prefix = matlab.lang.makeValidName(char(flModes(j)));
        extraVars = [extraVars, {[prefix '_Exists'], [prefix '_Matched'], [prefix '_Period_h'], [prefix '_DiffPercent'], [prefix '_CandidateID']}]; %#ok<AGROW>
    end
    vars = [baseVars, extraVars];
    vars = vars(ismember(vars, M.Properties.VariableNames));
    T = M(:, vars);
end

function S = make_retention_summary(M, keyVars)
    keyVars = cellstr(keyVars);
    if isempty(M)
        S = table();
        return;
    end
    [U,~,ic] = unique(M(:, keyVars), 'rows', 'stable');
    n = height(U);
    N_RawCandidates = zeros(n,1);
    N_RawEligible = zeros(n,1);
    N_CarryForward = zeros(n,1);
    N_HarmonicSensitive12h = zeros(n,1);
    RetentionPct_EligibleRaw = nan(n,1);
    RetentionPct_AllRaw = nan(n,1);

    for i = 1:n
        idx = ic == i;
        N_RawCandidates(i) = sum(idx);
        N_RawEligible(i) = sum(M.RawPassQC(idx));
        N_CarryForward(i) = sum(M.CarryForward(idx));
        N_HarmonicSensitive12h(i) = sum(M.HarmonicSensitive12hFlag(idx));
        if N_RawEligible(i) > 0
            RetentionPct_EligibleRaw(i) = 100 * N_CarryForward(i) / N_RawEligible(i);
        end
        if N_RawCandidates(i) > 0
            RetentionPct_AllRaw(i) = 100 * N_CarryForward(i) / N_RawCandidates(i);
        end
    end

    S = U;
    S.N_RawCandidates = N_RawCandidates;
    S.N_RawEligible = N_RawEligible;
    S.N_CarryForward = N_CarryForward;
    S.RetentionPct_EligibleRaw = RetentionPct_EligibleRaw;
    S.RetentionPct_AllRaw = RetentionPct_AllRaw;
    S.N_HarmonicSensitive12h = N_HarmonicSensitive12h;
end

function Q = build_qc_flags(M)
    if isempty(M)
        Q = table(); return;
    end
    flagMask = ~M.CarryForward | M.HarmonicSensitive12hFlag | contains(M.FullLadderSensitivityStatus, "sensitive", 'IgnoreCase', true);
    Q = M(flagMask, :);
end

function write_output_workbook(outXLSX, Settings, LoadSummary, allCandidates, Matched, CarryForward, RawOnly, HSubOnly, FLSens, RetBand, RetPhoto, RetPhotoBand, QCFlags)
    readme = {
        'Raw vs Selective-HSub ultradian period validation.'
        'Primary rule: Raw ultradian candidates are carried forward only when matched to a SEL_P360 HSub candidate within the configured period tolerance.'
        'Raw remains the biological signal. HSub is used only as validation.'
        'Full Ladder outputs are retained as sensitivity/stress-test flags, not as the primary validation rule.'
        'UR_12_18 is flagged as harmonic-sensitive because it is close to the first harmonic of a 24 h rhythm.'
        'CarryForward_Periods is the table to use in downstream validated-Raw analyses.'
        };
    writecell(readme(:), outXLSX, 'Sheet', 'README');
    writetable(Settings, outXLSX, 'Sheet', 'Settings');
    writetable(LoadSummary, outXLSX, 'Sheet', 'LoadSummary');
    writetable(allCandidates, outXLSX, 'Sheet', 'AllPeriodCandidates');
    writetable(Matched, outXLSX, 'Sheet', 'Matched_Periods_All');
    writetable(CarryForward, outXLSX, 'Sheet', 'CarryForward_Periods');
    writetable(RawOnly, outXLSX, 'Sheet', 'RawOnly_NotCarriedForward');
    writetable(HSubOnly, outXLSX, 'Sheet', 'HSubOnly_ResidualFeatures');
    writetable(FLSens, outXLSX, 'Sheet', 'FullLadder_Sensitivity');
    writetable(RetBand, outXLSX, 'Sheet', 'Retention_ByBand');
    writetable(RetPhoto, outXLSX, 'Sheet', 'Retention_ByPhotoperiod');
    writetable(RetPhotoBand, outXLSX, 'Sheet', 'Retention_ByPhotoBand');
    writetable(QCFlags, outXLSX, 'Sheet', 'QC_Flags');
end

function make_validation_figures(M, PrimaryHSub, figDir, dpi, ext, primaryMode)
    ensure_dir(figDir);

    % Figure 1: paired Raw vs primary HSub period scatter.
    hasPair = isfinite(M.RawPeriod_h) & isfinite(M.PrimaryHSubPeriod_h);
    if any(hasPair)
        f = figure('Color','w','Position',[100 100 850 700]);
        scatter(M.RawPeriod_h(hasPair), M.PrimaryHSubPeriod_h(hasPair), 36, 'filled');
        hold on;
        minP = min([M.RawPeriod_h(hasPair); M.PrimaryHSubPeriod_h(hasPair)], [], 'omitnan');
        maxP = max([M.RawPeriod_h(hasPair); M.PrimaryHSubPeriod_h(hasPair)], [], 'omitnan');
        x = linspace(max(0.1,minP*0.9), maxP*1.1, 100);
        plot(x, x, 'k-', 'LineWidth', 1.2);
        plot(x, x*1.15, 'k--', 'LineWidth', 0.8);
        plot(x, x/1.15, 'k--', 'LineWidth', 0.8);
        xlabel('Raw ridge period (h)', 'FontWeight','bold');
        ylabel(sprintf('%s ridge period (h)', char(primaryMode)), 'FontWeight','bold');
        title('Raw versus Selective-HSub ultradian period agreement', 'FontWeight','bold');
        set(gca,'FontName','Times New Roman','Box','off','TickDir','out');
        axis square;
        exportgraphics(f, fullfile(figDir, ['Raw_vs_' char(primaryMode) '_PeriodScatter' ext]), 'Resolution', dpi);
        close(f);
    end

    % Figure 2: histogram overlay.
    rawP = M.RawPeriod_h(M.RawPassQC & isfinite(M.RawPeriod_h));
    hsubP = PrimaryHSub.MedianRidgePeriod_h(candidate_passes_qc(PrimaryHSub, 0, 0, false) & isfinite(PrimaryHSub.MedianRidgePeriod_h));
    if ~isempty(rawP) || ~isempty(hsubP)
        f = figure('Color','w','Position',[100 100 900 650]);
        hold on;
        edges = 1:0.5:18;
        if ~isempty(rawP), histogram(rawP, edges, 'Normalization','probability', 'DisplayStyle','stairs', 'LineWidth',1.5); end
        if ~isempty(hsubP), histogram(hsubP, edges, 'Normalization','probability', 'DisplayStyle','stairs', 'LineWidth',1.5); end
        xlabel('Period (h)', 'FontWeight','bold');
        ylabel('Proportion of candidates', 'FontWeight','bold');
        title('Raw and Selective-HSub candidate period distributions', 'FontWeight','bold');
        legend({'Raw','Selective-HSub'}, 'Location','best', 'Box','off');
        set(gca,'FontName','Times New Roman','Box','off','TickDir','out');
        exportgraphics(f, fullfile(figDir, ['Raw_vs_' char(primaryMode) '_PeriodHistogram' ext]), 'Resolution', dpi);
        close(f);
    end

    % Figure 3: retention by band.
    RetBand = make_retention_summary(M, "BandName");
    if ~isempty(RetBand)
        f = figure('Color','w','Position',[100 100 900 650]);
        bar(categorical(RetBand.BandName), RetBand.RetentionPct_EligibleRaw);
        ylabel('Validated retention (% of eligible Raw)', 'FontWeight','bold');
        xlabel('Band', 'FontWeight','bold');
        title('HSub-supported Raw ultradian candidate retention by band', 'FontWeight','bold');
        set(gca,'FontName','Times New Roman','Box','off','TickDir','out');
        ylim([0 100]);
        exportgraphics(f, fullfile(figDir, ['Retention_ByBand' ext]), 'Resolution', dpi);
        close(f);
    end

    % Figure 4: retention by photoperiod.
    RetPhoto = make_retention_summary(M, "Photoperiod_h");
    if ~isempty(RetPhoto)
        f = figure('Color','w','Position',[100 100 900 650]);
        bar(categorical(string(RetPhoto.Photoperiod_h)), RetPhoto.RetentionPct_EligibleRaw);
        ylabel('Validated retention (% of eligible Raw)', 'FontWeight','bold');
        xlabel('Photoperiod / light duration (h)', 'FontWeight','bold');
        title('HSub-supported Raw ultradian candidate retention by photoperiod', 'FontWeight','bold');
        set(gca,'FontName','Times New Roman','Box','off','TickDir','out');
        ylim([0 100]);
        exportgraphics(f, fullfile(figDir, ['Retention_ByPhotoperiod' ext]), 'Resolution', dpi);
        close(f);
    end

    % Figure 5: period difference for carried-forward candidates.
    C = M(M.CarryForward & isfinite(M.PeriodDiffPercent), :);
    if ~isempty(C)
        f = figure('Color','w','Position',[100 100 900 650]);
        scatter(categorical(C.BandName), C.PeriodDiffPercent, 36, 'filled');
        ylabel('Raw vs Selective-HSub period difference (%)', 'FontWeight','bold');
        xlabel('Band', 'FontWeight','bold');
        title('Period agreement among carried-forward candidates', 'FontWeight','bold');
        yline(15, 'k--', '15% tolerance');
        set(gca,'FontName','Times New Roman','Box','off','TickDir','out');
        exportgraphics(f, fullfile(figDir, ['CarryForward_PeriodDifference' ext]), 'Resolution', dpi);
        close(f);
    end
end

function ensure_dir(p)
    if ~isfolder(p), mkdir(p); end
end

function delete_if_exists(p)
    if isfile(p), delete(p); end
end

function log_line(fid, fmt, varargin)
    msg = sprintf(fmt, varargin{:});
    fprintf('%s\n', msg);
    if fid > 0
        fprintf(fid, '[%s] %s\n', datestr(now,31), msg);
    end
end

function fclose_if_open(fid)
    if ~isempty(fid) && fid > 0
        fclose(fid);
    end
end
